[win]
system_libs = [
  "ADVAPI32.dll",
  "COMCTL32.dll",
  "COMDLG32.dll",
  "DBGHELP.dll",
  "GDI32.dll",
  "KERNEL32.dll",
  "OLE32.dll",
  "OLEAUT32.dll",
  "RPCRT4.dll",
  "SHELL32.dll",
  "USER32.dll",
  "VERSION.dll",
  "WINMM.dll",
  "WS2_32.dll",
]

[[runtime_profiles]]
name = "hikcamera-win32"
arch_dir = "conda-packages/hikcamera-mvs/sources/5.0.1-20260512/win32/bin"
entries = ["MvCameraControl.dll", "MvISPControl.dll"]
system_libs = "win"

[[runtime_profiles]]
name = "hikcamera-win64"
arch_dir = "conda-packages/hikcamera-mvs/sources/5.0.1-20260512/win64/bin"
entries = ["MvCameraControl.dll", "MvISPControl.dll"]
system_libs = "win"
