[workspace]
name = "hikcamera-rs"
channels = ["https://vidlg.github.io/conda-channel", "conda-forge"]
platforms = ["win-64", "linux-64"]

[dependencies]
clangdev = "18.*"
lefthook = "*"
llvm-tools = "18.*"
nodejs = "*"
pnpm = "*"
python = "*"

[target.win-64.dependencies]
hikcamera-mvs-runtime = "0.1.*"
