[workspace]
name = "hikcamera-rs"
channels = ["https://xiaoze-cn.github.io/Conda-Packages", "conda-forge"]
platforms = ["win-64", "linux-64"]

[dependencies]
clangdev = "18.*"
lefthook = "*"
llvm-tools = "18.*"
nodejs = "*"
pnpm = "*"
python = "*"

[target.win-64.dependencies]
hikcamera-mvs = "==5.0.1"
