//! Raw FFI bindings for the HikCamera MVS C SDK.
//!
//! Bindings are generated at build time from the `hikcamera-mvs` conda package installed by pixi.
//! Most users should use the safe `hikcamera` crate instead.
//!
//! Status-code constants (`MV_OK`, `MV_E_*`, `MV_ALG_*`) are generated separately as `i32`.
//! This matches the SDK's `int` return values without changing other SDK constants generated by bindgen.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

include!(concat!(env!("OUT_DIR"), "/status_codes.rs"));
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
