//! Raw FFI bindings for the HikCamera MVS (industrial camera) C SDK.
//!
//! Generated by [`bindgen`](https://docs.rs/bindgen) against the vendored
//! headers in [`include/`](https://github.com/xiaoze-cn/hikcamera-rs/tree/main/crates/hikcamera-sys/include)
//! at build time. The high-level safe wrapper lives in the `hikcamera` crate;
//! prefer it over using these bindings directly.
//!
//! # Symbol naming
//!
//! Symbol names follow the upstream C conventions (PascalCase functions,
//! UPPER_CASE constants, snake_case typedefs), so the default rust naming
//! lints are relaxed below.
//!
//! # Status-code representation
//!
//! The SDK declares two kinds of integer constants via `#define`, and they
//! have **different natural types** in Rust:
//!
//! | Kind | Used as | Natural Rust type |
//! |------|---------|-------------------|
//! | Status codes (`MV_OK`, `MV_E_*`, `MV_ALG_*`) | Return-value comparisons against `int`-returning SDK functions | `i32` |
//! | Enum-parameter values (`MV_ACCESS_*`, pixel formats, trigger modes) | Function arguments declared `unsigned int` | `u32` |
//!
//! Bindgen alone can't emit these as `i32` — it sees the bare `0x80000000`-style
//! literals and refuses to write them into an `i32` constant because Rust
//! (unlike C) does not silently wrap out-of-range integer literals. None of
//! `bindgen`'s existing options (`MacroTypeVariation::Signed`, the
//! `int_macro` callback, `IntKind::Custom`) re-encodes the literal; they all
//! hit the same `literal out of range for i32` error.
//!
//! `build.rs` therefore does two things:
//!
//! 1. **Generates `OUT_DIR/status_codes.rs` itself** by parsing
//!    `MvErrorDefine.h` + `MvISPErrorDefine.h`, emitting each status code as
//!    `pub const MV_E_HANDLE: i32 = 0x80000000_u32 as i32;` (preserves the
//!    hex form, matches the SDK's `int` return bit pattern).
//! 2. **Blocklists those two headers in bindgen** so they aren't double-
//!    emitted as `u32` constants from the bindings file.
//!
//! The result: status codes are `i32`, matching the SDK's `c_int` return
//! type, and the safe wrapper compares them with **zero casts** at call
//! sites. See `developer/bindings-generation` in the project site for the
//! full design rationale and the alternatives that were rejected.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

include!(concat!(env!("OUT_DIR"), "/status_codes.rs"));
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
